import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { ethers } from "ethers";

import Web3Modal from "web3modal";

import WalletConnectProvider from "@walletconnect/web3-provider";
// Create connector

const providerOptions = {
    walletconnect: {
        display: {
            name: "Mobile",
        },
        package: WalletConnectProvider,
        options: {
            infuraId: "9bde5ac2ebc84a20928bd82154cd5f6b", // required
        },
    },
};

import { swapTest, tokenTest } from "../utils/utils";

export default function Home() {
    const connectWallet = async () => {
        if (window) {
            const web3Modal = new Web3Modal({
                network: "rinkeby", // optional
                cacheProvider: true, // optional
                providerOptions, // required
            });
            const instance = await web3Modal.connect();
            const provider = new ethers.providers.Web3Provider(instance);
            console.log(await provider.listAccounts());

            const signer = provider.getSigner();
        }
    };

    const createSwap = async () => {
        await swapTest();
        await tokenTest();
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Swapify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.title}>Welcome to Swapify</h1>
            <button onClick={() => connectWallet()}>Wallet Connect</button>
            <button onClick={() => createSwap()}>Create swap</button>
        </div>
    );
}
