import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Web3 from "web3";
import { providers } from "ethers";
import { ethers } from "ethers";

import Web3Modal from "web3modal";

import WalletConnectProvider from "@walletconnect/web3-provider";
// Create connector

const providerOptions = {
    walletconnect: {
        display: {
            name: "Mobile",
        },
        package: WalletConnectProvider,
        options: {
            infuraId: "9bde5ac2ebc84a20928bd82154cd5f6b", // required
        },
    },
};

export default function Home() {
    const web3Modal = new Web3Modal({
        network: "rinkeby", // optional
        cacheProvider: true, // optional
        providerOptions, // required
    });
    const connectWallet = async () => {
        const instance = await web3Modal.connect();
        const provider = new ethers.providers.Web3Provider(instance);
        console.log(await provider.listAccounts());

        const signer = provider.getSigner();
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Swapify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className={styles.title}>Welcome to Swapify</h1>
            <button onClick={() => connectWallet()}>Wallet Connect</button>
        </div>
    );
}
